=== tvolegario/training2020/OlegarioEx20/config/flightlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   targetNamespace="http://www.77global.org/flightlist" 
		   xmlns:tns="http://www.77global.org/flightlist" 
		   elementFormDefault="qualified">
	<xs:element name="flightlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="flight" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="passengers" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="passenger" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string"/>
												<xs:attribute name="seat">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:pattern value="\d[A-Z]"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="date" type="xs:date"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="number" type="xs:integer"/>
						<xs:attribute name="origin">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="BOS"/>
									<xs:enumeration value="SJU"/>
									<xs:enumeration value="SFO"/>
									<xs:enumeration value="JFK"/>
									<xs:enumeration value="DCA"/>
									<xs:enumeration value="MAD"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="dest">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="BOS"/>
									<xs:enumeration value="SJU"/>
									<xs:enumeration value="SFO"/>
									<xs:enumeration value="JFK"/>
									<xs:enumeration value="DCA"/>
									<xs:enumeration value="MAD"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
</xs:schema>

=== tvolegario/training2020/OlegarioEx20/config/flightlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DOCTYPE flightlist SYSTEM "flightlist.dtd"-->
<flightlist xmlns="http://www.77global.org/flightlist" 
		    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:schemaLocation="http://www.77global.org/flightlist
		   					   flightlist.xsd">
		   					   
	<flight number="1" origin="BOS" dest="SJU">
		<passengers date="12-04-2012">
			<passenger name="Laura" seat="1A"/>
			<passenger name="Anna" seat="1B"/>
		</passengers>
		<passengers date="12-5-2012">
			<passenger name="Tatiana" seat="1C"/>
			<passenger name="Candy" seat="1D"/>
		</passengers>
	</flight>
	
	<flight number="2" origin="SFO" dest="JFK">
		<passengers date="12-4-2012">
			<passenger name="Charlie" seat="1A"/>
			<passenger name="Ivan" seat="1B"/>
		</passengers>
		<passengers date="12-5-2012">
			<passenger name="Dan" seat="1C"/>
			<passenger name="Li" seat="1D"/>
		</passengers>
	</flight>
	
	<flight number="3" origin="NYC" dest="MRY">
		<passengers date="12-5-2012">
			<passenger name="Eva" seat="2A"/>
			<passenger name="Joshua" seat="2B"/>
		</passengers>
		<passengers date="12-6-2012">
			<passenger name="Crizzy" seat="2C"/>
			<passenger name="Lu" seat="2D"/>
		</passengers>
	</flight>
</flightlist>
